### PR TITLE
optimization to save on API calls

### PR DESCRIPTION
**Pull request by iandouglas**
instead of doing an editIssue call for each child-parent assignment, and again for every dependency, let's just modify the whole body one time and send a single editIssue call.

### CODE REVIEW

**Review by adamzolyak — CHANGES_REQUESTED** [review]
old code 19.4 seconds to execute; new code 10.7 seconds to execute.  Love it 🙌! 

since the bump of the probot version was merged, change references of `issues.edit` to `issues.update`; otherwise looks great!

**Comment by iandouglas** [comment]
Should save on a ton of API calls too! Surprised it cut the time in half :)

I updated the `.edit` calls to be `.update`, not in an easy place to check other conflicts, etc., sorry :(

**Review by adamzolyak — APPROVED** [review]
🚢🚢🚢

**Comment by iandouglas** [comment]
@adamzolyak Would you mind checking out this merge conflict fix and giving it another test? I *think* it'll work okay...

**Comment by adamzolyak** [comment]
tested; working as expected 👍

**Pull request merged**
